/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

import javax.swing.ImageIcon;

/**
 *
 * @author michel.sanchez
 */
public class Interface extends javax.swing.JFrame {

    private Object display;
        public float primerNumero;
        public float segundoNumero;
        public String operador;
        
        
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/calculator.png")); 
        this.setIconImage(icon.getImage());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        btnMas = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setBackground(new java.awt.Color(220, 220, 220));
        txtResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        panel.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 340, 90));

        btnMas.setBackground(new java.awt.Color(153, 153, 153));
        btnMas.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnMas.setText("+");
        btnMas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });
        panel.add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 70, 140));

        btnCero.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCero.setText("0");
        btnCero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });
        panel.add(btnCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 160, 60));

        btnPunto.setBackground(new java.awt.Color(153, 153, 153));
        btnPunto.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        panel.add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 70, 60));

        btnIgual.setBackground(new java.awt.Color(255, 102, 51));
        btnIgual.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        panel.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 70, 140));

        btnUno.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnUno.setText("1");
        btnUno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });
        panel.add(btnUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 70, 60));

        btnDos.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnDos.setText("2");
        btnDos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });
        panel.add(btnDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 70, 60));

        btnTres.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnTres.setText("3");
        btnTres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });
        panel.add(btnTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 70, 60));

        btnMenos.setBackground(new java.awt.Color(153, 153, 153));
        btnMenos.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        panel.add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 60));

        btnCuatro.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });
        panel.add(btnCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, 60));

        btnCinco.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnCinco.setText("5");
        btnCinco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });
        panel.add(btnCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 70, 60));

        btnSeis.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSeis.setText("6");
        btnSeis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });
        panel.add(btnSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 70, 60));

        btnPor.setBackground(new java.awt.Color(153, 153, 153));
        btnPor.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnPor.setText("X");
        btnPor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorActionPerformed(evt);
            }
        });
        panel.add(btnPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 60));

        btnSiete.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnSiete.setText("7");
        btnSiete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        panel.add(btnSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, 60));

        btnOcho.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnOcho.setText("8");
        btnOcho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOchoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOchoMousePressed(evt);
            }
        });
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });
        panel.add(btnOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 70, 60));

        btnNueve.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnNueve.setText("9");
        btnNueve.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });
        panel.add(btnNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 70, 60));

        btnDividir.setBackground(new java.awt.Color(153, 153, 153));
        btnDividir.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnDividir.setText("÷");
        btnDividir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        panel.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, 60));

        btnC.setBackground(new java.awt.Color(0, 153, 255));
        btnC.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnC.setText("C");
        btnC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        panel.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, 60));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, 10));

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        this.primerNumero = Float.parseFloat(this.txtResultado.getText());
        this.operador="+";
        this.txtResultado.setText("");
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
this.txtResultado.setText(this.txtResultado.getText()+"0");        // TODO add your handling code here:
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if(!(this.txtResultado.getText().contains("."))) {
            this.txtResultado.setText(this.txtResultado.getText()+".");
        }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        this.segundoNumero = Float.parseFloat(this.txtResultado.getText());
        
        switch(this.operador){
            case "+":this.txtResultado.setText(sinCero(this.primerNumero+this.segundoNumero));break;
            case "-":this.txtResultado.setText(sinCero(this.primerNumero-this.segundoNumero));break;
            case "*":this.txtResultado.setText(sinCero(this.primerNumero*this.segundoNumero));break;
            case "/":this.txtResultado.setText(sinCero(this.primerNumero/this.segundoNumero));break;
            
        }
        
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        this.primerNumero = Float.parseFloat(this.txtResultado.getText());
            this.operador="-";
            this.txtResultado.setText("");
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorActionPerformed
         this.primerNumero = Float.parseFloat(this.txtResultado.getText());
            this.operador="x";
            this.txtResultado.setText("");
    }//GEN-LAST:event_btnPorActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
            this.txtResultado.setText(this.txtResultado.getText()+"8");
        
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        this.txtResultado.setText(this.txtResultado.getText()+"9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        this.primerNumero = Float.parseFloat(this.txtResultado.getText());
            this.operador="/";
            this.txtResultado.setText("");
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOchoMouseClicked
        
    }//GEN-LAST:event_btnOchoMouseClicked

    private void btnOchoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOchoMousePressed
   
    }//GEN-LAST:event_btnOchoMousePressed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        this.txtResultado.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    public String sinCero (float resultado){
        String retorno ="";
        retorno = Float.toString(resultado);
        
        if(resultado%1==0){
            retorno=retorno.substring(0, retorno.length () -2);
        }
        return retorno;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPor;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
